update azure-pipelines && add docker script

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -33,3 +33,68 @@ steps:
     docker push $(imageName)
     docker push $(latestImageName)
   displayName: 'Push docker image'
+
+
+
+
+- script: |
+    docker build -f Dockerfile -t $(imageName) .
+    docker login -u $(dockerId) -p $(pswd)
+    docker push $(imageName)
+
+- task: SSH
+  displayName: 'Run shell inline on remote machine'
+  inputs:
+    sshEndpoint: 'weihanli-vm'
+    runOptions: inline
+
+    inline: |
+     containers=$(docker ps -q --filter name=activityreservation)
+     if test -n "$containers"; then
+      docker stop $(docker ps -q --filter name=activityreservation) >> /dev/null 2>&1
+      rc=$?
+      if [[ $rc != 0 ]];
+      then
+       echo 'failed to stop container...'
+       exit $rc;
+      fi
+     fi
+     
+     containers1=$(docker ps -q -a --filter name=activityreservation)
+     if test -n "$containers1"; then
+      docker rm $(docker ps -q -a --filter name=activityreservation) >> /dev/null 2>&1
+      rc=$?
+      if [[ $rc != 0 ]];
+      then
+       echo 'failed to remove container...'
+       exit $rc;
+      fi
+     fi
+     
+     
+     docker pull $(imageName):latest >> /dev/null 2>&1
+     rc=$?
+     if [[ $rc != 0 ]];
+     then
+      echo 'failed to pull container...'
+      exit $rc;
+     fi
+     
+     docker run -d -p 7010:80 --name activityreservation --link redis:redis-server $(imageName):latest >> /dev/null 2>&1
+     rc=$?
+     if [[ $rc != 0 ]];
+     then
+      echo 'failed to run container...'
+      exit $rc;
+     fi
+     
+     danglings=$(docker images -f "dangling=true" -q)
+     if test -n "$danglings"; then
+      docker rmi $(docker images -f "dangling=true" -q) >> /dev/null 2>&1
+      rc=$?
+      if [[ $rc != 0 ]];
+      then
+       echo 'failed to remove danglings container...'
+       exit $rc;
+      fi
+     fi
